# Generated by Django 5.2.9 on 2025-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level_letter',
            field=models.CharField(blank=True, help_text='Например: А, Б, В, Е', max_length=1, verbose_name='Буква класса'),
        ),
    ]
