# Generated by Django 5.2.9 on 2025-12-13 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней попытки'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лучший результат (баллы)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
